### ISSUE TITLE
魅族7.1.1中找不到show方法

### ISSUE THREAD

**Issue by zmylls** [YuanKJ-/ExToast#4]
在魅族手机上出现这样的错误，楼主有什么建议吗？
03-08 20:36:59.666 23776-23776/systems.xos.car.toastextendview E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: systems.xos.car.toastextendview, PID: 23776
                                                                                 java.lang.NoSuchMethodError: No interface method show()V in class Landroid/app/ITransientNotification; or its super classes (declaration of 'android.app.ITransientNotification' appears in /system/framework/framework.jar)
                                                                                     at systems.xos.car.toastextendview.ExToast.show(ExToast.java:66)
                                                                                     at systems.xos.car.toastextendview.MainActivity.onCreate(MainActivity.java:24)
                                                                                     at android.app.Activity.performCreate(Activity.java:6765)
                                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1122)
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2825)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2937)
                                                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1645)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                                     at android.os.Looper.loop(Looper.java:203)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6451)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1134)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

**Comment by guohaiyang1992** [comment]
7.1.1 show 方法修改了，需要传入token ，也就说明此方法已经不奏效了，token 只能系统应用生成，so，此路不通

**Comment by zmylls** [comment]
不知道您有没有看过ToastCompat这个,好像是修改了Token的一个bug，但我不太理解。结合这个，能改做修改吗？
